#!/usr/bin/env python3
"""Build data/places.tsv: a small offline place-name + postcode index for instant autocomplete.

Source: GeoNames (https://www.geonames.org), licensed CC BY 4.0.
Usage:  python scripts/build_places.py [download-dir]
Downloads cities1000.zip, admin1CodesASCII.txt and the NL/BE/LU postcode files if missing.

Output columns (tab-separated, no header):
  kind(p=place, z=postcode)  name  alt-names(|-separated)  region  country-code  lat  lon  population
"""
import io
import os
import sys
import unicodedata
import urllib.request
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'places.tsv')
BASE = 'https://download.geonames.org/export/'

# Countries where every place with >= 1000 inhabitants is kept; elsewhere only larger towns.
CORE = {'NL', 'BE', 'LU', 'DE'}
COUNTRIES = set('nl,be,de,lu,fr,at,ch,li,dk,it,es,pt,ad,mc,sm,gb,ie,pl,cz,sk,hu,si,hr,ba,rs,me,mk,al,gr,bg,ro,se,no,fi,ee,lv,lt'.upper().split(','))
OTHER_MIN_POP = 10000
ALT_MIN_POP = 20000
POSTCODES = ['NL', 'BE', 'LU']


def fetch(dirname, name, url):
    path = os.path.join(dirname, name)
    if not os.path.exists(path):
        print('downloading', url)
        urllib.request.urlretrieve(url, path)
    return path


def read_zip(path, member):
    with zipfile.ZipFile(path) as z:
        return io.TextIOWrapper(z.open(member), encoding='utf-8').read().splitlines()


def norm(s):
    s = unicodedata.normalize('NFD', s)
    return ''.join(c for c in s if unicodedata.category(c) != 'Mn').lower()


def latin(s):
    return all(c.isascii() or unicodedata.name(c, '').startswith('LATIN') for c in s)


def clean(s):
    return s.replace('\t', ' ').replace('|', ' ').strip()


def main():
    dl = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '.geonames')
    os.makedirs(dl, exist_ok=True)
    admin1 = {}
    for line in open(fetch(dl, 'admin1CodesASCII.txt', BASE + 'dump/admin1CodesASCII.txt'), encoding='utf-8'):
        code, name, *_ = line.rstrip('\n').split('\t')
        admin1[code] = name

    rows = []
    for line in read_zip(fetch(dl, 'cities1000.zip', BASE + 'dump/cities1000.zip'), 'cities1000.txt'):
        f = line.split('\t')
        cc, fclass, pop = f[8], f[6], int(f[14] or 0)
        if cc not in COUNTRIES or fclass != 'P':
            continue
        if cc not in CORE and pop < OTHER_MIN_POP:
            continue
        name = clean(f[1])
        alts = []
        if pop >= ALT_MIN_POP:
            seen = {norm(name), norm(f[2])}
            for a in f[3].split(','):
                a = clean(a)
                if not a or len(a) > 30 or not a[0].isupper() or a.isupper() or not latin(a) or norm(a) in seen:
                    continue
                seen.add(norm(a))
                alts.append(a)
                if len(alts) >= 80:
                    break
        elif norm(f[2]) != norm(name):
            alts.append(clean(f[2]))
        region = admin1.get(f'{cc}.{f[10]}', '')
        rows.append(('p', name, '|'.join(alts), region, cc, f'{float(f[4]):.4f}', f'{float(f[5]):.4f}', str(pop)))

    for cc in POSTCODES:
        seen = set()
        for line in read_zip(fetch(dl, f'pc_{cc}.zip', f'{BASE}zip/{cc}.zip'), f'{cc}.txt'):
            f = line.split('\t')
            code = f[1].strip()
            if not f[9] or (code, f[2]) in seen:
                continue
            seen.add((code, f[2]))
            rows.append(('z', code, clean(f[2]), clean(f[3]), cc, f'{float(f[9]):.4f}', f'{float(f[10]):.4f}', '0'))

    with open(OUT, 'w', encoding='utf-8', newline='\n') as out:
        out.write('# GeoNames (https://www.geonames.org), CC BY 4.0. Generated by scripts/build_places.py\n')
        for r in rows:
            out.write('\t'.join(r) + '\n')
    print(f'wrote {len(rows)} rows to {OUT} ({os.path.getsize(OUT) // 1024} KiB)')


if __name__ == '__main__':
    main()
